services:
  mysql:
    image: mysql:8.0
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: qna_prod
      MYSQL_USER: qna
      MYSQL_PASSWORD: qna123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  backend:
    env_file:
      - ../.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qna-backend
    depends_on:
      - mysql
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: qna_prod
      DB_USER: qna
      DB_PASSWORD: qna123
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://3.35.209.31:8080"
    container_name: qna-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  mysql_data:
